apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: webapp-port
  selector:
    app: webapp
