apiVersion: v1
kind: Service
metadata:
  name: wcfservice
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: wcfservice-port
  selector:
    app: wcfservice
